language: node_js
node_js:
- '7'
install: npm install
script:
- node index.js
notifications:
  slack:
    rooms:
      - leanintuit:4TbhlQX6AdNBl5hTK0PubKnh#engineering_training
    on_success: always
    on_failure: always